-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
WHERE 
    SEX_UPON_INTAKE LIKE 'Intact%' 
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%'
    OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID;