-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, (SUM(FO.AMOUNT) * FD.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT FD
JOIN FOOD_ORDER FO USING (PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC, 
    PRODUCT_ID;